spring.application.name=VirtualBookshop
spring.datasource.url=jdbc:postgresql://localhost:5432/virtual_bookstore
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=your_jwt_secret_key
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.security=INFO
