spring.application.name=VirtualBookshop
spring.datasource.url=jdbc:postgresql://localhost:5432/virtual_bookstore
spring.datasource.username=postgres
spring.datasource.password=post123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=MySuperSecretKeyForJwt12345678901234567890
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.security=INFO
